/**
 * Slack / Discord-style :shortcode: → Unicode emoji.
 * Unknown shortcodes are left unchanged.
 */
const SHORTCODE_MAP = {
  point_right: "👉",
  point_left: "👈",
  point_up: "👆",
  point_down: "👇",
  backhand_index_pointing_right: "👉",
  backhand_index_pointing_left: "👈",
  two_hearts: "💕",
  heart: "❤️",
  hearts: "💕",
  blue_heart: "💙",
  green_heart: "💚",
  yellow_heart: "💛",
  purple_heart: "💜",
  orange_heart: "🧡",
  black_heart: "🖤",
  white_heart: "🤍",
  broken_heart: "💔",
  sparkles: "✨",
  star: "⭐",
  star2: "🌟",
  glowing_star: "🌟",
  herb: "🌿",
  seedling: "🌱",
  four_leaf_clover: "🍀",
  round_pushpin: "📍",
  pushpin: "📌",
  dna: "🧬",
  closed_lock_with_key: "🔐",
  lock: "🔒",
  unlock: "🔓",
  key: "🔑",
  check: "✅",
  white_check_mark: "✅",
  x: "❌",
  warning: "⚠️",
  exclamation: "❗",
  question: "❓",
  fire: "🔥",
  rocket: "🚀",
  trophy: "🏆",
  medal: "🏅",
  crown: "👑",
  gem: "💎",
  moneybag: "💰",
  dollar: "💵",
  credit_card: "💳",
  gift: "🎁",
  tada: "🎉",
  confetti_ball: "🎊",
  balloon: "🎈",
  thumbsup: "👍",
  thumbsdown: "👎",
  "+1": "👍",
  "-1": "👎",
  clap: "👏",
  pray: "🙏",
  muscle: "💪",
  eyes: "👀",
  eye: "👁️",
  smile: "😄",
  grin: "😁",
  joy: "😂",
  wink: "😉",
  blush: "😊",
  thinking: "🤔",
  sunglasses: "😎",
  sob: "😭",
  rage: "😡",
  skull: "💀",
  ghost: "👻",
  alien: "👽",
  robot: "🤖",
  sun: "☀️",
  sunny: "☀️",
  moon: "🌙",
  cloud: "☁️",
  rainbow: "🌈",
  zap: "⚡",
  snowflake: "❄️",
  umbrella: "☂️",
  coffee: "☕",
  beer: "🍺",
  wine_glass: "🍷",
  pizza: "🍕",
  hamburger: "🍔",
  apple: "🍎",
  banana: "🍌",
  cake: "🎂",
  cookie: "🍪",
  dog: "🐶",
  cat: "🐱",
  lion: "🦁",
  unicorn: "🦄",
  butterfly: "🦋",
  bee: "🐝",
  flower: "🌸",
  blossom: "🌸",
  rose: "🌹",
  tulip: "🌷",
  cherry_blossom: "🌸",
  globe: "🌍",
  earth_americas: "🌎",
  earth_africa: "🌍",
  flag_us: "🇺🇸",
  us: "🇺🇸",
  phone: "📱",
  computer: "💻",
  laptop: "💻",
  email: "📧",
  envelope: "✉️",
  link: "🔗",
  chart: "📈",
  chart_with_upwards_trend: "📈",
  bar_chart: "📊",
  clipboard: "📋",
  pencil: "✏️",
  memo: "📝",
  book: "📖",
  books: "📚",
  microscope: "🔬",
  pill: "💊",
  syringe: "💉",
  hospital: "🏥",
  stethoscope: "🩺",
  shield: "🛡️",
  hammer: "🔨",
  wrench: "🔧",
  gear: "⚙️",
  bulb: "💡",
  bell: "🔔",
  mute: "🔇",
  speaker: "🔊",
  music: "🎵",
  notes: "🎶",
  camera: "📷",
  video_camera: "📹",
  tv: "📺",
  movie_camera: "🎥",
  clock: "🕐",
  hourglass: "⏳",
  stopwatch: "⏱️",
  calendar: "📅",
  house: "🏠",
  office: "🏢",
  car: "🚗",
  airplane: "✈️",
  ship: "🚢",
  bike: "🚲",
  runner: "🏃",
  walk: "🚶",
  handshake: "🤝",
  wave: "👋",
  raised_hands: "🙌",
  ok_hand: "👌",
  v: "✌️",
  crossed_fingers: "🤞",
  infinity: "♾️",
  recycle: "♻️",
  copyright: "©️",
  registered: "®️",
  tm: "™️",
};

const SHORTCODE_RE = /:([a-z0-9_+-]+):/gi;

/**
 * @param {string} text
 * @returns {string}
 */
export function expandEmojiShortcodes(text) {
  if (!text || typeof text !== "string") return text;
  return text.replace(SHORTCODE_RE, (match, name) => {
    const emoji = SHORTCODE_MAP[name.toLowerCase()];
    return emoji ?? match;
  });
}

/**
 * Replace :shortcodes: inside a contenteditable root (styled editor).
 * @param {HTMLElement} root
 */
export function expandShortcodesInEditable(root) {
  if (!root) return;
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  const nodes = [];
  let node;
  while ((node = walker.nextNode())) nodes.push(node);
  for (const textNode of nodes) {
    const expanded = expandEmojiShortcodes(textNode.textContent);
    if (expanded !== textNode.textContent) {
      textNode.textContent = expanded;
    }
  }
}
